import type {
  ExperienceAcceptanceBaselineConfig,
  ExperienceComparisonSampleConfig,
  ExperienceDimensionConfig,
  LiveBalanceWaveSampleConfig,
  LongTermBalanceIndicatorConfig,
} from './types';

export const WUXIA_EXPERIENCE_DIMENSION_CONFIGS: ExperienceDimensionConfig[] = [
  {
    id: 'archetype_strength',
    label: 'Archetype strength',
    lifePhases: ['origin', 'childhood', 'early_route', 'midlife_consequence', 'legacy_endgame'],
    measurabilityClass: 'partial',
    interpretationGuide: 'Archetype family emerges with signal match beyond route label alone.',
    evidenceSources: ['p20/archetypeCoverage', 'p20/validationSlices'],
  },
  {
    id: 'replay_distinctiveness',
    label: 'Replay distinctiveness',
    lifePhases: ['origin', 'childhood', 'early_route', 'midlife_consequence'],
    measurabilityClass: 'partial',
    interpretationGuide: 'Cross-run novelty and overlap decay distinguish replays.',
    evidenceSources: ['p20/repetitionPressure', 'p20/replaySliceConfigs'],
  },
  {
    id: 'route_differentiation',
    label: 'Route differentiation',
    lifePhases: ['early_route', 'midlife_consequence'],
    measurabilityClass: 'partial',
    interpretationGuide: 'Route scheduling and path affinity produce distinct life paths.',
    evidenceSources: ['p11/scheduling', 'p20/wholeLifePacing'],
  },
  {
    id: 'stage_pacing_health',
    label: 'Stage pacing health',
    lifePhases: ['childhood', 'early_route', 'midlife_consequence', 'legacy_endgame'],
    measurabilityClass: 'explicit',
    interpretationGuide: 'Density and payoff spacing differ materially across archetypes.',
    evidenceSources: ['p20/wholeLifePacing', 'p20/archetypePacingProfiles'],
  },
  {
    id: 'mid_late_payoff',
    label: 'Mid/late payoff strength',
    lifePhases: ['midlife_consequence', 'legacy_endgame'],
    measurabilityClass: 'partial',
    interpretationGuide: 'Consequence engagement and payoff spacing carry stakes.',
    evidenceSources: ['p17/consequenceSurfaces', 'p20/replaySliceConfigs'],
  },
  {
    id: 'legacy_resonance',
    label: 'Legacy resonance',
    lifePhases: ['legacy_endgame'],
    measurabilityClass: 'partial',
    interpretationGuide: 'Transmission, rupture, and successor signals align with life path.',
    evidenceSources: ['p18/legacySurfaces', 'p20/replaySliceConfigs'],
  },
  {
    id: 'endgame_aftertaste',
    label: 'Endgame aftertaste',
    lifePhases: ['legacy_endgame'],
    measurabilityClass: 'partial',
    interpretationGuide: 'Endgame category and historical memory tone match arc closure.',
    evidenceSources: ['p19/endgameCategories', 'p19/historicalMemory'],
  },
];

export const WUXIA_EXPERIENCE_ACCEPTANCE_BASELINE_CONFIGS: ExperienceAcceptanceBaselineConfig[] = [
  {
    id: 'p23_baseline_archetype_replay',
    label: 'Archetype and replay baseline',
    dimension: 'archetype_strength',
    strongerSliceId: 'p20_slice_midlife_consequence',
    weakerSliceId: 'p20_slice_origin_early',
    minimumScoreDelta: 0.08,
    scoringFields: ['archetypeScore', 'signalMatchCount', 'distinctiveBeyondRoute'],
    authoringNotes: 'Martial origin early slice vs merchant pacing thin-archetype slice.',
  },
  {
    id: 'p23_baseline_stage_pacing',
    label: 'Stage pacing baseline',
    dimension: 'stage_pacing_health',
    strongerSliceId: 'p20_slice_midlife_consequence',
    weakerSliceId: 'p20_slice_wealth_pacing',
    minimumScoreDelta: 0.06,
    scoringFields: ['pacingMultiplier', 'densityDelta', 'payoffSpacing'],
    authoringNotes: 'Martial vs wealth pacing rhythm differentiation.',
  },
  {
    id: 'p23_baseline_mid_late_payoff',
    label: 'Mid/late payoff baseline',
    dimension: 'mid_late_payoff',
    strongerSliceId: 'p20_slice_midlife_consequence',
    weakerSliceId: 'p20_slice_wealth_pacing',
    minimumScoreDelta: 0.08,
    scoringFields: ['consequenceEngagement', 'payoffSpacing', 'factionExposure'],
    authoringNotes: 'Demonic midlife consequence vs wealth pacing flat payoff.',
  },
  {
    id: 'p23_baseline_legacy_endgame',
    label: 'Legacy and endgame baseline',
    dimension: 'legacy_resonance',
    strongerSliceId: 'p20_slice_legacy_endgame',
    weakerSliceId: 'p20_slice_hermit_closure',
    minimumScoreDelta: 0.1,
    scoringFields: ['legacyShapeScore', 'endgameCategoryMatch', 'memoryToneAlignment'],
    authoringNotes: 'Scholar teaching legacy vs hermit fade closure.',
  },
];

export const WUXIA_EXPERIENCE_COMPARISON_SAMPLE_CONFIGS: ExperienceComparisonSampleConfig[] = [
  {
    id: 'p23_cmp_archetype_replay',
    label: 'Archetype replay comparison',
    dimension: 'archetype_strength',
    strongerSliceId: 'p20_slice_midlife_consequence',
    weakerSliceId: 'p20_slice_origin_early',
    comparisonMetric: 'archetype_distinctiveness_delta',
    wholeLife: true,
    sliceLevel: true,
    authoringNotes: 'Whole-life archetype emergence vs thin hermit replay.',
  },
  {
    id: 'p23_cmp_stage_pacing',
    label: 'Stage pacing comparison',
    dimension: 'stage_pacing_health',
    strongerSliceId: 'p20_slice_midlife_consequence',
    weakerSliceId: 'p20_slice_wealth_pacing',
    comparisonMetric: 'pacing_multiplier_delta',
    wholeLife: true,
    sliceLevel: true,
    authoringNotes: 'Martial density vs merchant delayed payoff rhythm.',
  },
  {
    id: 'p23_cmp_mid_late_payoff',
    label: 'Mid/late payoff comparison',
    dimension: 'mid_late_payoff',
    strongerSliceId: 'p20_slice_midlife_consequence',
    weakerSliceId: 'p20_slice_wealth_pacing',
    comparisonMetric: 'consequence_payoff_delta',
    wholeLife: false,
    sliceLevel: true,
    authoringNotes: 'Consequence-weighted midlife vs flat merchant payoff.',
  },
  {
    id: 'p23_cmp_legacy_endgame',
    label: 'Legacy endgame comparison',
    dimension: 'endgame_aftertaste',
    strongerSliceId: 'p20_slice_legacy_endgame',
    weakerSliceId: 'p20_slice_hermit_closure',
    comparisonMetric: 'legacy_memory_resonance_delta',
    wholeLife: false,
    sliceLevel: true,
    authoringNotes: 'Scholar legacy memory vs isolated fade aftertaste.',
  },
];

export const WUXIA_LONG_TERM_BALANCE_INDICATOR_CONFIGS: LongTermBalanceIndicatorConfig[] = [
  {
    id: 'p23_ind_archetype_stability',
    label: 'Archetype stability',
    dimension: 'archetype_strength',
    interpretation: 'Share of archetype families emerging with distinctive signal match.',
    healthyRange: { min: 0.7, max: 1.0 },
    baselineValue: 0.78,
    comparisonNotes: 'Rising = families stay distinguishable; falling = homogenization.',
  },
  {
    id: 'p23_ind_replay_novelty',
    label: 'Replay novelty',
    dimension: 'replay_distinctiveness',
    interpretation: 'Normalized novelty boost from repetition pressure tuning.',
    healthyRange: { min: 0.55, max: 0.9 },
    baselineValue: 0.62,
    comparisonNotes: 'Rising = less repetitive replays; falling = overlap crowding.',
  },
  {
    id: 'p23_ind_stage_pacing_health',
    label: 'Stage pacing health',
    dimension: 'stage_pacing_health',
    interpretation: 'Pacing multiplier delta health across representative archetype pairs.',
    healthyRange: { min: 0.5, max: 0.95 },
    baselineValue: 0.68,
    comparisonNotes: 'Stable high = distinct rhythms; collapse = homogenization.',
  },
  {
    id: 'p23_ind_mid_late_payoff',
    label: 'Mid/late payoff strength',
    dimension: 'mid_late_payoff',
    interpretation: 'Midlife consequence engagement delta for stronger vs weaker slices.',
    healthyRange: { min: 0.45, max: 0.9 },
    baselineValue: 0.58,
    comparisonNotes: 'Rising = later-life stakes strengthen.',
  },
  {
    id: 'p23_ind_legacy_endgame_resonance',
    label: 'Legacy/endgame resonance',
    dimension: 'legacy_resonance',
    interpretation: 'Combined endgame category and historical memory alignment.',
    healthyRange: { min: 0.5, max: 0.92 },
    baselineValue: 0.64,
    comparisonNotes: 'Rising = closures land with aftertaste.',
  },
];

export const WUXIA_LIVE_BALANCE_WAVE_SAMPLE_CONFIGS: LiveBalanceWaveSampleConfig[] = [
  {
    id: 'p23_wave_high_value_pacing_tune',
    label: 'Low-volume pacing tuning',
    waveClass: 'high_value_tuning',
    targetDimension: 'stage_pacing_health',
    contentVolumeDelta: 0,
    experienceDeltaExpected: 0.09,
    authoringNotes: 'P22 hermit closure spacing tune improves pacing without new events.',
  },
  {
    id: 'p23_wave_low_value_volume',
    label: 'Low-value volume wave',
    waveClass: 'low_value_detection',
    targetDimension: 'replay_distinctiveness',
    contentVolumeDelta: 5,
    experienceDeltaExpected: 0.01,
    authoringNotes: 'Simulated pool expansion with flat replay novelty — should fail acceptance.',
  },
  {
    id: 'p23_wave_tuning_redirect',
    label: 'Tuning redirection sample',
    waveClass: 'tuning_redirection',
    targetDimension: 'mid_late_payoff',
    contentVolumeDelta: 3,
    experienceDeltaExpected: 0.12,
    redirectedFromWaveId: 'p23_wave_low_value_volume',
    authoringNotes: 'Redirects from volume wave to P22 midlife consequence expansion + tuning.',
  },
  {
    id: 'p23_wave_full_life_operation',
    label: 'Bounded full-life balance operation',
    waveClass: 'full_life_operation',
    targetDimension: 'archetype_strength',
    contentVolumeDelta: 3,
    experienceDeltaExpected: 0.1,
    authoringNotes: 'Early/mid/late/endgame surfaces in one bounded comparison wave.',
  },
];
