import type {
  BaselinePoolConfig,
  LibraryCoverageExpectation,
  LiveOpsContentWaveConfig,
  TuningSampleConfig,
} from './types';

export const WUXIA_BASELINE_POOL_CONFIGS: BaselinePoolConfig[] = [
  {
    id: 'p22_pool_origin',
    label: '出身与开局池',
    lifePhase: 'origin',
    sourcePaths: ['./lines/origin.json'],
    eventTagPrefixes: ['origin', 'p16', 'p22'],
    minimumEventCount: 6,
    knownThinAreas: ['frontier_military', 'streetborn', 'scholar_house variance'],
    comparisonNotes: 'Compare origin event count and originId coverage against WUXIA_ORIGIN_SURFACES.',
  },
  {
    id: 'p22_pool_childhood_shaping',
    label: '童年塑形池',
    lifePhase: 'childhood',
    sourcePaths: ['./lines/general.json', './lines/origin.json'],
    eventTagPrefixes: ['childhood', 'formative', 'p16', 'p22'],
    minimumEventCount: 8,
    knownThinAreas: ['streetborn formative band', 'guidance-conditioned milestones'],
    comparisonNotes: 'Age 0–12 formal spine plus childhoodShapingRules coverage.',
  },
  {
    id: 'p22_pool_early_route',
    label: '早期路线分歧池',
    lifePhase: 'early_route',
    sourcePaths: ['./lines/p9-remediation.json', './lines/p21-content-samples.json', './lines/p22-content-expansions.json'],
    eventTagPrefixes: ['route', 'p9', 'p21', 'p22'],
    minimumEventCount: 5,
    knownThinAreas: ['wealth merchant early fork', 'explorer wanderer reinforcement'],
    comparisonNotes: 'Route reinforcement events with narrativeScheduling.routePoints.',
  },
  {
    id: 'p22_pool_midlife_consequence',
    label: '中年后果与身份延续池',
    lifePhase: 'midlife_consequence',
    sourcePaths: ['./lines/love.json', './lines/faction-revelation.json', './lines/middle-age-career.json', './lines/p22-content-expansions.json'],
    eventTagPrefixes: ['consequence', 'faction', 'relationship', 'p17', 'p22'],
    minimumEventCount: 10,
    knownThinAreas: ['mentor obligation continuation', 'sect exposure sustained role'],
    comparisonNotes: 'Relationship + faction consequence patterns with mid-life age bands.',
  },
  {
    id: 'p22_pool_legacy_endgame',
    label: '传承终局与历史记忆池',
    lifePhase: 'legacy_endgame',
    sourcePaths: ['./lines/elderly-legacy.json', './lines/p22-content-expansions.json'],
    eventTagPrefixes: ['legacy', 'endgame', 'memory', 'p18', 'p19', 'p22'],
    minimumEventCount: 8,
    knownThinAreas: ['hermit fade closure', 'wealth dynasty memory tone'],
    comparisonNotes: 'Legacy outcome + endgame category + historical memory differentiation.',
  },
];

export const WUXIA_LIBRARY_COVERAGE_EXPECTATIONS: LibraryCoverageExpectation[] = [
  {
    poolId: 'p22_pool_origin',
    minimumEventCount: 6,
    minimumDistinctRouteSignals: 3,
    minimumArchetypeTags: 4,
    thinCoverageThreshold: 0.45,
    repetitiveOverlapThreshold: 0.7,
    authoringNotes: 'Origin pool must cover martial, merchant, scholar, poor, frontier, streetborn.',
  },
  {
    poolId: 'p22_pool_childhood_shaping',
    minimumEventCount: 8,
    minimumDistinctRouteSignals: 2,
    minimumArchetypeTags: 3,
    thinCoverageThreshold: 0.5,
    repetitiveOverlapThreshold: 0.75,
    authoringNotes: 'Childhood milestones should diverge by shaping tendencies, not repeat training loops.',
  },
  {
    poolId: 'p22_pool_early_route',
    minimumEventCount: 5,
    minimumDistinctRouteSignals: 4,
    minimumArchetypeTags: 3,
    thinCoverageThreshold: 0.4,
    repetitiveOverlapThreshold: 0.65,
    authoringNotes: 'Early route reinforcement must differ across scholarly, wealth, demonic, martial families.',
  },
  {
    poolId: 'p22_pool_midlife_consequence',
    minimumEventCount: 10,
    minimumDistinctRouteSignals: 3,
    minimumArchetypeTags: 4,
    thinCoverageThreshold: 0.45,
    repetitiveOverlapThreshold: 0.7,
    authoringNotes: 'Mid-life consequence events should sustain mentor, faction, and social-role identities.',
  },
  {
    poolId: 'p22_pool_legacy_endgame',
    minimumEventCount: 8,
    minimumDistinctRouteSignals: 2,
    minimumArchetypeTags: 3,
    thinCoverageThreshold: 0.5,
    repetitiveOverlapThreshold: 0.72,
    authoringNotes: 'Late-life closure must support teaching legacy, fade legacy, and infamous echo tones.',
  },
];

export const WUXIA_LIVE_OPS_WAVE_CONFIGS: LiveOpsContentWaveConfig[] = [
  {
    id: 'p22_wave_early_growth',
    label: '早期成长内容波次',
    lifePhase: 'early_life',
    targetPoolId: 'p22_pool_origin',
    targetWeakness: 'frontier_military and streetborn origin variance',
    eventIds: ['p22_origin_frontier_orphan', 'p22_childhood_street_shaping', 'p22_wave_early_frontier_growth'],
    workflowSteps: [
      'audit:pool-coverage',
      'author:event-json',
      'validate:authoringSemantics',
      'gate:p22',
      'compare:baseline-pool',
    ],
  },
  {
    id: 'p22_wave_mid_consequence',
    label: '中年后果内容波次',
    lifePhase: 'mid_life',
    targetPoolId: 'p22_pool_midlife_consequence',
    targetWeakness: 'wealth merchant and mentor obligation mid-life support',
    eventIds: ['p22_early_wealth_route_fork', 'p22_relationship_mentor_obligation', 'p22_faction_sect_continuation', 'p22_wave_mid_merchant_identity'],
    workflowSteps: [
      'audit:weak-spot',
      'author:event-json',
      'validate:production-matrix',
      'gate:p22',
      'tune:route-distribution',
    ],
  },
  {
    id: 'p22_wave_late_closure',
    label: '晚期传承终局内容波次',
    lifePhase: 'late_life',
    targetPoolId: 'p22_pool_legacy_endgame',
    targetWeakness: 'hermit fade and teaching legacy closure differentiation',
    eventIds: ['p22_legacy_teaching_succession', 'p22_endgame_hermit_memory', 'p22_wave_late_fade_closure'],
    workflowSteps: [
      'audit:closure-pool',
      'author:event-json',
      'validate:coverage-matrix',
      'gate:p22',
      'tune:closure-density',
    ],
  },
];

/** Representative live-ops tuning samples — config-only workflow proof (US-020–US-022). */
export const WUXIA_LIVE_OPS_TUNING_SAMPLE_CONFIGS: TuningSampleConfig[] = [
  {
    id: 'p22_tune_route_wealth_distribution',
    label: '商贾早期路线分布调优',
    tuningClass: 'route_distribution',
    targetFieldPath: 'events.p22_early_wealth_route_fork.metadata.pathAffinity.wealth',
    baselineValue: 0.8,
    tunedValue: 1.0,
    validationMetric: 'wealth_route_event_share',
    expectedDelta: 'increase',
    authoringNotes: 'Boost wealth pathAffinity on P22 early route divergence sample.',
  },
  {
    id: 'p22_tune_hermit_closure_density',
    label: '隐逸终局密度调优',
    tuningClass: 'stage_pacing',
    targetFieldPath: 'archetypePacingProfiles.p20_hermit_withdrawal.stageProfiles.stage_30_40.payoffSpacingMultiplier',
    baselineValue: 1.4,
    tunedValue: 1.15,
    validationMetric: 'hermit_closure_payoff_density',
    expectedDelta: 'tighten_spacing',
    authoringNotes: 'Tighten hermit late-life payoff spacing after P22 closure pool expansion.',
  },
  {
    id: 'p22_tune_wealth_archetype_coverage',
    label: '商贾谱系覆盖调优',
    tuningClass: 'archetype_coverage',
    targetFieldPath: 'archetypeFamilyConfigs.p20_wealth_merchant.baseWeight',
    baselineValue: 1.0,
    tunedValue: 1.12,
    validationMetric: 'wealth_merchant_emergence_score',
    expectedDelta: 'increase',
    authoringNotes: 'Raise wealth merchant baseWeight so expanded pools are not crowded out.',
  },
];
