import type {
  AlignmentComparisonConfig,
  AlignmentIndicatorConfig,
  PlaytestCalibrationBaselineConfig,
  PlaytestComparisonSampleConfig,
  PlaytestDimensionConfig,
  PlaytestFeedbackSchemaConfig,
  RcComparisonSampleConfig,
  RcEvaluationSchemaConfig,
} from './types';
import { RC_BIAS_DIRECTIONS, RC_RELEASE_READINESS_STATES } from './types';

export const WUXIA_PLAYTEST_DIMENSION_CONFIGS: PlaytestDimensionConfig[] = [
  {
    id: 'first_run_readability',
    label: 'First-run readability',
    lifePhases: ['origin', 'childhood'],
    measurabilityClass: 'human_testable',
    interpretationGuide: 'Opening clarity — can a new player understand what matters?',
    evidenceSources: ['p8/playability', 'p16/originSurfaces', 'p24/calibrationBaselines'],
  },
  {
    id: 'onboarding_motivation',
    label: 'Onboarding motivation',
    lifePhases: ['childhood', 'early_route'],
    measurabilityClass: 'human_testable',
    interpretationGuide: 'Momentum to continue after first session.',
    evidenceSources: ['p7/activePlanning', 'p9/mandatoryLane', 'p24/calibrationBaselines'],
  },
  {
    id: 'replay_distinctiveness',
    label: 'Replay distinctiveness',
    lifePhases: ['early_route', 'midlife_consequence'],
    measurabilityClass: 'partial_proxy',
    interpretationGuide: 'Cross-run felt difference beyond content count.',
    evidenceSources: ['p20/repetitionPressure', 'p20/replaySliceConfigs'],
  },
  {
    id: 'route_differentiation',
    label: 'Route differentiation',
    lifePhases: ['early_route', 'midlife_consequence'],
    measurabilityClass: 'partial_proxy',
    interpretationGuide: 'Path legibility and meaningful route contrast.',
    evidenceSources: ['p11/scheduling', 'p20/wholeLifePacing'],
  },
  {
    id: 'late_game_payoff',
    label: 'Late-game payoff',
    lifePhases: ['midlife_consequence', 'legacy_endgame'],
    measurabilityClass: 'partial_proxy',
    interpretationGuide: 'Consequence weight and memorable stakes.',
    evidenceSources: ['p17/consequenceSurfaces', 'p23/midLatePayoff'],
  },
  {
    id: 'ending_aftertaste',
    label: 'Ending aftertaste',
    lifePhases: ['legacy_endgame'],
    measurabilityClass: 'partial_proxy',
    interpretationGuide: 'Post-run resonance and closure distinctness.',
    evidenceSources: ['p19/endgameCategories', 'p19/historicalMemory'],
  },
];

export const WUXIA_PLAYTEST_FEEDBACK_SCHEMA: PlaytestFeedbackSchemaConfig = {
  schemaVersion: 'p24-v1',
  capturePurpose: 'Structured human playtest judgments for calibration and RC review.',
  fields: [
    {
      fieldId: 'respondentId',
      label: 'Respondent ID',
      fieldType: 'string',
      required: false,
      semantics: 'Anonymous or panel identifier for triage grouping.',
    },
    {
      fieldId: 'sessionId',
      label: 'Session ID',
      fieldType: 'string',
      required: true,
      semantics: 'Unique play session for linking multiple dimension scores.',
    },
    {
      fieldId: 'dimension',
      label: 'Playtest dimension',
      fieldType: 'enum',
      required: true,
      semantics: 'Which outward experience dimension is being judged.',
      enumValues: [
        'first_run_readability',
        'onboarding_motivation',
        'replay_distinctiveness',
        'route_differentiation',
        'late_game_payoff',
        'ending_aftertaste',
      ],
    },
    {
      fieldId: 'humanScore',
      label: 'Human score',
      fieldType: 'number',
      required: true,
      semantics: 'Normalized 0–1 or 1–5 Likert mapped to 0–1 for comparison.',
    },
    {
      fieldId: 'confidence',
      label: 'Reviewer confidence',
      fieldType: 'enum',
      required: true,
      semantics: 'How confident the reviewer is in this judgment.',
      enumValues: ['low', 'medium', 'high'],
    },
    {
      fieldId: 'observedBlockers',
      label: 'Observed blockers',
      fieldType: 'text',
      required: false,
      semantics: 'Free-text blockers (confusion, drop-off, flat payoff, etc.).',
    },
    {
      fieldId: 'continueIntent',
      label: 'Continue intent',
      fieldType: 'enum',
      required: false,
      semantics: 'Would the player continue after this phase?',
      enumValues: ['drop', 'uncertain', 'continue', 'replay'],
    },
    {
      fieldId: 'buildId',
      label: 'Build ID',
      fieldType: 'string',
      required: true,
      semantics: 'Candidate build under RC review.',
    },
  ],
  triageHints: [
    'Group by dimension and buildId for wave comparison.',
    'Flag sessions where humanScore < 0.4 with high confidence as RC blockers.',
    'Cross-reference observedBlockers with alignment gap direction.',
  ],
};

export const WUXIA_RC_EVALUATION_SCHEMA: RcEvaluationSchemaConfig = {
  schemaVersion: 'p24-v1',
  evaluationPurpose: 'Explicit RC candidate-build judgment inputs and outputs.',
  fields: [
    {
      fieldId: 'buildId',
      label: 'Build ID',
      direction: 'input',
      fieldType: 'string',
      semantics: 'Candidate build identifier.',
    },
    {
      fieldId: 'candidateLabel',
      label: 'Candidate label',
      direction: 'input',
      fieldType: 'string',
      semantics: 'Human-readable RC wave label.',
    },
    {
      fieldId: 'internalHealthScore',
      label: 'Internal health score',
      direction: 'input',
      fieldType: 'number',
      semantics: 'Aggregate internal gate health 0–1 (P12/P23 upstream).',
    },
    {
      fieldId: 'externalAppealScore',
      label: 'External appeal score',
      direction: 'input',
      fieldType: 'number',
      semantics: 'Playtest proxy or human aggregate 0–1.',
    },
    {
      fieldId: 'alignmentGap',
      label: 'Alignment gap',
      direction: 'output',
      fieldType: 'number',
      semantics: 'internalHealthScore - externalAppealScore; positive = overestimate.',
    },
    {
      fieldId: 'biasDirection',
      label: 'Bias direction',
      direction: 'output',
      fieldType: 'enum',
      semantics: 'Whether internal reports over- or under-estimate player experience.',
      enumValues: [...RC_BIAS_DIRECTIONS],
    },
    {
      fieldId: 'releaseReadiness',
      label: 'Release readiness',
      direction: 'output',
      fieldType: 'enum',
      semantics:
        'RC decision based on combined internal and external evidence. Out-of-scope deferrals are recorded in deferredItems, not as a readiness state.',
      enumValues: [...RC_RELEASE_READINESS_STATES],
    },
    {
      fieldId: 'blockers',
      label: 'RC blockers',
      direction: 'output',
      fieldType: 'text',
      semantics: 'Documented player-facing blockers preventing ship.',
    },
    {
      fieldId: 'strengths',
      label: 'RC strengths',
      direction: 'output',
      fieldType: 'text',
      semantics: 'Documented outward strengths supporting ship.',
    },
    {
      fieldId: 'deferredItems',
      label: 'Deferred items',
      direction: 'output',
      fieldType: 'text',
      semantics: 'Problems explicitly deferred beyond P24 with reason.',
    },
  ],
  releaseReadinessThresholds: {
    minInternalHealth: 0.65,
    minExternalAppeal: 0.55,
    maxAlignmentGap: 0.15,
  },
};

export const WUXIA_ALIGNMENT_COMPARISON_CONFIGS: AlignmentComparisonConfig[] = [
  {
    id: 'p24_cmp_onboarding_clarity',
    label: 'Onboarding clarity alignment',
    dimension: 'first_run_readability',
    internalEvidenceSource: 'p8/playability early-age survival',
    externalEvidenceSource: 'p24/playtest first-run proxy',
    overestimateThreshold: 0.15,
    underestimateThreshold: -0.15,
    authoringNotes: 'Internal survival can pass while opening prose feels opaque.',
  },
  {
    id: 'p24_cmp_replay_motivation',
    label: 'Replay motivation alignment',
    dimension: 'replay_distinctiveness',
    internalEvidenceSource: 'p20/repetitionPressure novelty',
    externalEvidenceSource: 'p24/playtest replay proxy',
    overestimateThreshold: 0.15,
    underestimateThreshold: -0.15,
    authoringNotes: 'Overlap decay can rise without felt replay desire.',
  },
  {
    id: 'p24_cmp_route_readability',
    label: 'Route readability alignment',
    dimension: 'route_differentiation',
    internalEvidenceSource: 'p11/route scheduling health',
    externalEvidenceSource: 'p24/playtest route proxy',
    overestimateThreshold: 0.15,
    underestimateThreshold: -0.15,
    authoringNotes: 'Scheduled route points ≠ legible path contrast.',
  },
  {
    id: 'p24_cmp_payoff_strength',
    label: 'Payoff strength alignment',
    dimension: 'late_game_payoff',
    internalEvidenceSource: 'p23/midLatePayoff baseline',
    externalEvidenceSource: 'p24/playtest payoff proxy',
    overestimateThreshold: 0.15,
    underestimateThreshold: -0.15,
    authoringNotes: 'Consequence flags can pass while stakes feel flat.',
  },
  {
    id: 'p24_cmp_ending_resonance',
    label: 'Ending resonance alignment',
    dimension: 'ending_aftertaste',
    internalEvidenceSource: 'p19/endgame category match',
    externalEvidenceSource: 'p24/playtest aftertaste proxy',
    overestimateThreshold: 0.15,
    underestimateThreshold: -0.15,
    authoringNotes: 'Category alignment without lasting aftertaste.',
  },
];

export const WUXIA_PLAYTEST_CALIBRATION_BASELINE_CONFIGS: PlaytestCalibrationBaselineConfig[] = [
  {
    id: 'p24_baseline_first_run',
    label: 'First-run readability baseline',
    dimension: 'first_run_readability',
    strongerSliceId: 'p20_slice_origin_early',
    weakerSliceId: 'p20_slice_hermit_closure',
    minimumScoreDelta: 0.1,
    scoringFields: ['earlyClarity', 'originLegibility', 'choiceComprehension'],
    authoringNotes: 'Martial origin early growth vs hermit fade closure.',
  },
  {
    id: 'p24_baseline_onboarding',
    label: 'Onboarding motivation baseline',
    dimension: 'onboarding_motivation',
    strongerSliceId: 'p20_slice_origin_early',
    weakerSliceId: 'p20_slice_wealth_pacing',
    minimumScoreDelta: 0.08,
    scoringFields: ['continueMomentum', 'earlyPayoff', 'routeHook'],
    authoringNotes: 'Early martial momentum vs delayed merchant pacing.',
  },
  {
    id: 'p24_baseline_replay',
    label: 'Replay distinctiveness baseline',
    dimension: 'replay_distinctiveness',
    strongerSliceId: 'p20_slice_midlife_consequence',
    weakerSliceId: 'p20_slice_origin_early',
    minimumScoreDelta: 0.08,
    scoringFields: ['crossRunNovelty', 'overlapDecay', 'pathContrast'],
    authoringNotes: 'Demonic midlife vs thin origin replay.',
  },
  {
    id: 'p24_baseline_route',
    label: 'Route differentiation baseline',
    dimension: 'route_differentiation',
    strongerSliceId: 'p20_slice_midlife_consequence',
    weakerSliceId: 'p20_slice_wealth_pacing',
    minimumScoreDelta: 0.08,
    scoringFields: ['routeLegibility', 'pathAffinity', 'schedulingContrast'],
    authoringNotes: 'Evil midlife path vs neutral merchant pacing.',
  },
  {
    id: 'p24_baseline_late_payoff',
    label: 'Late-game payoff baseline',
    dimension: 'late_game_payoff',
    strongerSliceId: 'p20_slice_midlife_consequence',
    weakerSliceId: 'p20_slice_wealth_pacing',
    minimumScoreDelta: 0.08,
    scoringFields: ['consequenceWeight', 'stakesRecall', 'payoffSpacing'],
    authoringNotes: 'Consequence-weighted midlife vs flat merchant payoff.',
  },
  {
    id: 'p24_baseline_ending',
    label: 'Ending aftertaste baseline',
    dimension: 'ending_aftertaste',
    strongerSliceId: 'p20_slice_legacy_endgame',
    weakerSliceId: 'p20_slice_hermit_closure',
    minimumScoreDelta: 0.1,
    scoringFields: ['aftertasteResonance', 'closureDistinctness', 'memoryTone'],
    authoringNotes: 'Scholar legacy memory vs hermit fade aftertaste.',
  },
];

export const WUXIA_PLAYTEST_COMPARISON_SAMPLE_CONFIGS: PlaytestComparisonSampleConfig[] = [
  {
    id: 'p24_cmp_first_run_onboarding',
    label: 'First-run and onboarding comparison',
    dimension: 'first_run_readability',
    strongerSliceId: 'p20_slice_origin_early',
    weakerSliceId: 'p20_slice_hermit_closure',
    comparisonMetric: 'first_run_clarity_delta',
    lifePhaseBand: 'early',
    authoringNotes: 'Opening clarity for new-player first session.',
  },
  {
    id: 'p24_cmp_onboarding_motivation',
    label: 'Onboarding motivation comparison',
    dimension: 'onboarding_motivation',
    strongerSliceId: 'p20_slice_origin_early',
    weakerSliceId: 'p20_slice_wealth_pacing',
    comparisonMetric: 'onboarding_momentum_delta',
    lifePhaseBand: 'early',
    authoringNotes: 'Continue intent proxy for first-session momentum.',
  },
  {
    id: 'p24_cmp_replay_route',
    label: 'Replay and route distinction comparison',
    dimension: 'replay_distinctiveness',
    strongerSliceId: 'p20_slice_midlife_consequence',
    weakerSliceId: 'p20_slice_origin_early',
    comparisonMetric: 'replay_route_delta',
    lifePhaseBand: 'mid',
    authoringNotes: 'Cross-run and route contrast for mid-life band.',
  },
  {
    id: 'p24_cmp_late_ending',
    label: 'Late payoff and ending comparison',
    dimension: 'ending_aftertaste',
    strongerSliceId: 'p20_slice_legacy_endgame',
    weakerSliceId: 'p20_slice_hermit_closure',
    comparisonMetric: 'payoff_aftertaste_delta',
    lifePhaseBand: 'late_end',
    authoringNotes: 'Late stakes and post-run aftertaste for RC closure.',
  },
];

export const WUXIA_ALIGNMENT_INDICATOR_CONFIGS: AlignmentIndicatorConfig[] = [
  {
    id: 'p24_ind_onboarding_clarity',
    label: 'Onboarding clarity alignment',
    dimension: 'first_run_readability',
    interpretation: 'Internal early-clarity proxy vs playtest comprehension.',
    healthyRange: { min: 0.85, max: 1.0 },
    baselineValue: 0.87,
    comparisonNotes: 'currentValue = 1 - |alignmentGap|; falling = internal overestimate of first-run clarity.',
  },
  {
    id: 'p24_ind_replay_motivation',
    label: 'Replay motivation alignment',
    dimension: 'replay_distinctiveness',
    interpretation: 'P20 replay novelty vs felt replay desire proxy.',
    healthyRange: { min: 0.85, max: 1.0 },
    baselineValue: 0.9,
    comparisonNotes: 'currentValue = 1 - |alignmentGap|; falling = replay desire weaker than internal novelty.',
  },
  {
    id: 'p24_ind_route_readability',
    label: 'Route readability alignment',
    dimension: 'route_differentiation',
    interpretation: 'Scheduling health vs route legibility proxy.',
    healthyRange: { min: 0.85, max: 1.0 },
    baselineValue: 0.92,
    comparisonNotes: 'currentValue = 1 - |alignmentGap|; collapse = routes feel same despite scheduling pass.',
  },
  {
    id: 'p24_ind_payoff_strength',
    label: 'Payoff strength alignment',
    dimension: 'late_game_payoff',
    interpretation: 'Consequence scores vs memorable stakes proxy.',
    healthyRange: { min: 0.85, max: 1.0 },
    baselineValue: 0.91,
    comparisonNotes: 'currentValue = 1 - |alignmentGap|; rising gap = flat stakes despite consequence flags.',
  },
  {
    id: 'p24_ind_ending_resonance',
    label: 'Ending resonance alignment',
    dimension: 'ending_aftertaste',
    interpretation: 'P19 category match vs post-run aftertaste proxy.',
    healthyRange: { min: 0.85, max: 1.0 },
    baselineValue: 0.9,
    comparisonNotes: 'currentValue = 1 - |alignmentGap|; gap = category passes without resonant closure.',
  },
];

export const WUXIA_RC_COMPARISON_SAMPLE_CONFIGS: RcComparisonSampleConfig[] = [
  {
    id: 'p24_rc_weak_outward',
    label: 'Strong internal, weak outward RC sample',
    sampleClass: 'weak_outward_experience',
    targetDimension: 'first_run_readability',
    internalHealthScore: 0.82,
    externalAppealScore: 0.38,
    expectedAlignmentBias: 'overestimate',
    authoringNotes: 'P23 matrix passes while first-run proxy fails — false-positive RC risk.',
  },
  {
    id: 'p24_rc_feedback_redirect',
    label: 'Player feedback redirection sample',
    sampleClass: 'feedback_redirection',
    targetDimension: 'onboarding_motivation',
    internalHealthScore: 0.74,
    externalAppealScore: 0.42,
    expectedAlignmentBias: 'overestimate',
    fixDescription: 'Redirect from volume expansion to P22 origin pool clarity tune.',
    redirectedFromSampleId: 'p24_rc_weak_outward',
    authoringNotes: 'Playtest feedback changes preferred fix from internal-only tuning.',
  },
  {
    id: 'p24_rc_targeted_fix',
    label: 'Targeted fix validation sample',
    sampleClass: 'targeted_fix_validation',
    targetDimension: 'onboarding_motivation',
    internalHealthScore: 0.76,
    externalAppealScore: 0.68,
    expectedAlignmentBias: 'aligned',
    fixDescription: 'Origin pool clarity tune improves onboarding proxy measurably.',
    redirectedFromSampleId: 'p24_rc_feedback_redirect',
    authoringNotes: 'RC reporting validates outward improvement after targeted fix.',
  },
];
